### ISSUE TITLE
wrong argument

### ISSUE THREAD

**Issue by cuobai** [Hakanaou/deepLuna#10]
(for the newest version)
there may be a bug when I try to insert the text.
here is my [table.txt](https://github.com/Hakanaou/deepLuna/files/7165344/table.txt)
![圖片](https://user-images.githubusercontent.com/74899300/133339120-4531050b-b454-48dd-bc67-99476b9639ff.png)

**Comment by Hakanaou** [comment]
This issue was also corrected earlier today, you can download the new version of the script.
