### ISSUE TITLE
Not opening

### ISSUE THREAD

**Issue by Zac91281** [Hakanaou/deepLuna#14]
Whenever I try to open deepLuna, python opens and closes it instantly. I'm using the latest version and the files are placed with the needed extracted files from the game. My knowledge is pretty lay, so I don't know what to do.

**Comment by Hakanaou** [comment]
Sorry for th delay. What are you opening deepLuna with? Pyzo, IDLE or command line? I would recommend you to use Pyzo - install it, then File/Open and select deepLuna.py. Then go to Run/Run file as script, or press Ctrl + Shift + E (or Cmd + Shift + E on Mac) to launch deepLuna. Latest version changes pretty quickly, please download the latest one once more.

**Comment by Zac91281** [comment]
Sorry for bother you again, but trying open deepluna through Pyzo, I had the following issue: 

> Traceback (most recent call last):
>   File "C:\Users\username\AppData\Roaming\yuzu\load\01001DC01486A000\deepLuna\deepLuna.py", line 24, in <module>
>     import requests
> ModuleNotFoundError: No module named 'requests'

**Comment by Hakanaou** [comment]
In the subwindow of Pyzo you got the error, you have a prompt - you can type here "pip install requests", hit return and wait until it finishes. Then redo the same with "pip install Pillow".

**Comment by Zac91281** [comment]
It worked perfectly! Thank you very much for your attention

**Comment by Hakanaou** [comment]
You're welcome :)! I'll be closing the issue for now, if you have another problem, just open a new one.
