### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by EmiyaArc** [Hakanaou/deepLuna#17]
what should i do ?
![image](https://user-images.githubusercontent.com/92046312/136243882-2f5695be-9110-42b2-b162-ae7707494ac8.png)

**Comment by Hakanaou** [comment]
Please follow the procedure as described in the Readme, i.e. install a python distribution from the official website and then an IDE like Pyzo. In Pyzo, open deepLuna.py, then click on Run/Run file as a script.
If you get a complaint about "requests" or "PIL", simply write in Pyzo's console (where you see these errors appear) "pip install requests" or "pip install Pillow".
If you still have a problem tell me, we'll then try to solve it!

**Comment by EmiyaArc** [comment]
well.. thank you but..
![image](https://user-images.githubusercontent.com/92046312/136260788-71c5630c-6e58-42e5-b06b-a79a82107ae4.png)
Did i miss something ?
![image](https://user-images.githubusercontent.com/92046312/136260990-458e8116-1568-4342-b2ee-a11e29d4f3e5.png)

I've followed [Clover Moon's](https://rentry.co/9ehyf) instructions
and reached the "Setting up deepLuna" step.

**Comment by VoidZ47** [comment]
You have to type:
                                  Pip install (module name)
In this case:
                          Pip install requests

Do this for any missing modules

**Comment by EmiyaArc** [comment]
I did what you asked me
I struggled a bit and searched youtube and found solutions

But I didn't find a solution to this...
![image](https://user-images.githubusercontent.com/92046312/136296887-0b6e8e88-339c-4ef0-b79f-af3964aa2a2a.png)
