### ISSUE TITLE
New Function

### ISSUE THREAD

**Issue by HigherOrderLogic** [Hakanaou/deepLuna#2]
Can you make a function to repack it into nsp file or make a new patch for the script or something like that?

**Comment by CloverMoonTL** [comment]
To make a patch easily you can use any emulator, as they support layeredFS. Just click with RMB on the game icon:
![image](https://user-images.githubusercontent.com/90000241/131982666-817be4e6-3add-4b5d-8f3b-13ae189f30b2.png)
And pick ```Open mods directory```, create new folder called whatever you like (for example ```deepLuna```) an in this folder you create another folder named ```romfs```. Then you insert there modified ```script_text.mrg```.
This is how it should looks like. Ignore ```jaX``` folders, they are for font changes.
![image](https://user-images.githubusercontent.com/90000241/131983086-5c211bd8-4dc7-4472-9bfb-4270d218a34c.png)
If you modified your Switch to have CFW, it probably supports layeredFS so making patch is this easy too, but method depends on CFW I think. As the most people prefer to play VNs on their computers, I described method for emulators.

I think this info should be in readme too.

**Comment by HigherOrderLogic** [comment]
> To make a patch easily you can use any emulator, as they support layeredFS. Just click with RMB on the game icon:
> ![image](https://user-images.githubusercontent.com/90000241/131982666-817be4e6-3add-4b5d-8f3b-13ae189f30b2.png)
> And pick `Open mods directory`, create new folder called whatever you like (for example `deepLuna`) an in this folder you create another folder named `romfs`. Then you insert there modified `script_text.mrg`.
> This is how it should looks like. Ignore `jaX` folders, they are for font changes.
> ![image](https://user-images.githubusercontent.com/90000241/131983086-5c211bd8-4dc7-4472-9bfb-4270d218a34c.png)
> If you modified your Switch to have CFW, it probably supports layeredFS so making patch is this easy too, but method depends on CFW I think. As the most people prefer to play VNs on their computers, I described method for emulators.
> 
> I think this info should be in readme too.

That's what I did on my first attempt, but the text is still Japanese, what could have I done wrong?

**Comment by CloverMoonTL** [comment]
Make sure you inserted translated file, not JP one.
And keep in mind that prologue (one time only scene at the beginning) is movie, so the script_text.mrg cannot change it.

**Comment by Hakanaou** [comment]
@HigherOrderLogic : Unfortunately, I won't be adding an option to repack everything, since this is completely out of scope for a unique Python script such as deepLuna. @CloverMoonTL showed a very simple way to do extract and reinject the main resources using the emulator itself. Otherwise, you have tools such as hactool that are able to do the same thing (I put the link in the readme file).
Moreover, deepLuna is already patching the file containing the text of the game, which is script_text.mrg. For that, once you finish translating, simply click on "Insert" and the game will patch the file.
