### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by jeremoople** [Hakanaou/deepLuna#3]
Every time I try to run deepLuna.py in IDLE or Pyzo, I get this error:
```
Traceback (most recent call last):
  File "F:\tsukihime\deepLuna-main\deepLuna-main\deepLuna.py", line 18, in <module>
    from PIL import ImageTk, Image
ModuleNotFoundError: No module named 'PIL'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\tsuikihime\deepLuna-main\deepLuna-main\deepLuna.py", line 20, in <module>
    install("Pillow")
NameError: name 'install' is not defined
>>> 
```

I'm not used to installing programs using Python as opposed to like, a setup wizard, so I could very well just be making a basic newbie mistake, but still, I don't know where to go from here.

**Comment by requinDr** [comment]
Open your cmd and type
pip install Pillow
wait for it to be installed, and then type
pip install requests

That's how I solved the issue
