### ISSUE TITLE
Decode error on new build

### ISSUE THREAD

**Issue by SkyAshpd** [Hakanaou/deepLuna#32]
I decide to check new build, and it's give a error when i try to press "Extract Text" or "Open translation".
Traceback (most recent call last):
  File \luna\ui\start_window.py", line 166, in extract_database
    tl_db = TranslationDb.from_mrg(
  File \luna\translation_db.py", line 387, in from_mrg
    strings_by_offset[i] = data.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

**Comment by rschlaikjer** [comment]
Hi, can you confirm what MRGs you are using to initialize the database?

**Comment by SkyAshpd** [comment]
Script_text.mrg and allscr.mrg by extract from game 1.0.2 version (without any patch or etc) and from work with previous version. Both dont work, while work fine on old deepluna version.

**Comment by rschlaikjer** [comment]
Hrm, that's pretty strange. I am using the exact same MRGs and it appears to work fine - 
```
ross@mjolnir:/h/r/deepLuna$ cp ~/.../v131072/pfs/7a85ff8daf43afa5a026f9f7d6033166.1/{script_text,allscr}.mrg  ./
'/.../v131072/pfs/7a85ff8daf43afa5a026f9f7d6033166.1/script_text.mrg' -> './script_text.mrg'
'/.../v131072/pfs/7a85ff8daf43afa5a026f9f7d6033166.1/allscr.mrg' -> './allscr.mrg'
ross@mjolnir:/h/r/deepLuna$ md5sum *.mrg
6b0a80a132c6c737683772698c1f8530  allscr.mrg
3656e7ccfd0228f80ff5849dbec9ae13  script_text.mrg
ross@mjolnir:/h/r/deepLuna$ ./luna_cli.py --extract-mrg && echo "Parsed OK"
Failed to parse command _STGS(0,,0,800,0)#)
Failed to parse command _SQK2(11,2,2,100,-1,0,0,0,0)+)
Failed to parse command _MFAD(,,`001:8000,,`011:0)0)
Failed to parse command _STTR,0,26)
Failed to parse command _STZ4(5,498,498,498,498,0,0,0)gb)
Parsed OK
```

Do you have the exact same MD5sum for the MRG files you are using? What OS is this on? Do you have any cached .pyc files that might be causing problems?

**Comment by SkyAshpd** [comment]
Take fews MRG's and tried it on win10 - it didn't work, but tried it on Linux and it worked.  Really strange, maybe something with win10
