### ISSUE TITLE
Insertion Error

### ISSUE THREAD

**Issue by CChandraa** [Hakanaou/deepLuna#36]
When I try to insert the script, this error shows up and I assume the insertion isn't working, since implementing the MRGs in the game does nothing.
![image](https://user-images.githubusercontent.com/103993665/164394311-f6f59f6b-116e-4324-a184-08df9a24fcc1.png)

**Comment by rschlaikjer** [comment]
You have an old version of deepluna, please be sure to use the latest version on main.

**Comment by CChandraa** [comment]
![image](https://user-images.githubusercontent.com/103993665/164473866-6a7fbfa4-3f5f-4412-a0bb-1a06a6b26fcb.png)
Getting this error when extracting text, and a similar error during the running of the script that doesn't seem to stop anything(?).

**Comment by CChandraa** [comment]
Tried moving it around a bunch, ending up finding a location that worked(no idea why it worked specifically there), and the insertion seems to be working properly. Actually went through with trying to run the game properly this time, and it seems to be working! Thanks a lot for your help, would've never gotten to get this stuff installed with your help. 

~~Really hope some other issue doesn't end up coming up.~~
