### ISSUE TITLE
ModuleNotFoundError (I do have the module installed)

### ISSUE THREAD

**Issue by Arthurfogo7** [Hakanaou/deepLuna#4]
Traceback (most recent call last):
  File "C:\Users\arthu\Desktop\deepLuna-main\deepLuna-main\deepLuna.py", line 18, in <module>
    from PIL import ImageTk, Image
ModuleNotFoundError: No module named 'PIL'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\arthu\Desktop\deepLuna-main\deepLuna-main\deepLuna.py", line 20, in <module>
    install("Pillow")
NameError: name 'install' is not defined

The problem here is that when I try to run the script on IDE this errors occurs and I just don't know what to do since I already have everything needed installed.

**Comment by requinDr** [comment]
Execute on your cmd:
pip install Pillow
After that it should work.

**Comment by Hakanaou** [comment]
The PIL module should be installed as @requinDr said, by typing in the IDE console or in the cmd (if you added Python to the PATH) by typing
pip install Pillow
Even though the module is called with PIL, its real name is Pillow.
As for the other error, it's because deepLuna tries to install itself Pillow if it is not found - this was an experimental function, but since it doesn't seem to work properly, maybe I'll simply suppress it.
If it's till not working, I will try to think what to do.

**Comment by Arthurfogo7** [comment]
![Sem título57](https://user-images.githubusercontent.com/85951083/132552357-075f1119-4b17-464c-9515-ce2e5ee4a128.png)
![Sem título58](https://user-images.githubusercontent.com/85951083/132552362-a91fc275-488e-46cb-98d2-9280e2b2dbb7.png)
I really have no idea why that is happening to me...
I have all the modules installed.

**Comment by Hakanaou** [comment]
That seems to be related to your IDE/system, since the tkinter issue is very strange.
What version of Python are you using? Have you tried with another IDE, for example IDLE, that you get with the Python distribution itself?

**Comment by Arthurfogo7** [comment]
This time I tried to run the script on IDE and got so successfully install PIL and TK, but an different error occurred. 

Python 3.7.8 (tags/v3.7.8:4b47a5b6ba, Jun 28 2020, 08:53:46) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
==== RESTART: C:\Users\arthu\Desktop\deepLuna-main\deepLuna-main\deepLuna.py ===
Traceback (most recent call last):
  File "C:\Users\arthu\Desktop\deepLuna-main\deepLuna-main\deepLuna.py", line 17, in <module>
    from PIL import ImageTk, Image
  File "C:\Users\arthu\Desktop\deepLuna-main\deepLuna-main\PIL\ImageTk.py", line 31, in <module>
    from . import Image
  File "C:\Users\arthu\Desktop\deepLuna-main\deepLuna-main\PIL\Image.py", line 94, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (C:\Users\arthu\Desktop\deepLuna-main\deepLuna-main\PIL\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\arthu\Desktop\deepLuna-main\deepLuna-main\deepLuna.py", line 19, in <module>
    install("Pillow")
NameError: name 'install' is not defined
>>>

**Comment by Hakanaou** [comment]
Ok, this is already much better. To correct this, simply install the missing module by typing in the Python console in the IDE the following line:

pip install Pillow

This should correct the issue.
Or did you already do this?

**Comment by Arthurfogo7** [comment]
I have already done this, but I think maybe there is some kind of problem with the version of Pillow I'm using, since TK didn't work for me either when I installed it through cmd. I had to get it from Activetcl. Well, I'll try to reinstall pillow and see what happens, maybe there's some other way to install PIL.

**Comment by Hakanaou** [comment]
Maybe there is a conflict between your cmd installation and the python distribution of your IDE. There if you can to reinstall Pillow, and then also use maybe another IDE (I recommend pyzo). If it still doesn't work, tell me, and I'll try to think about something else.

**Comment by Arthurfogo7** [comment]
So I installed Pyzo and then the problem changed. Tkinter is installed, but maybe something is missing.

Python 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) on Windows (64 bits).
This is the Pyzo interpreter with integrated event loop for PYQT5.
Type 'help' for help, type '?' for a list of *magic* commands.
Running script: "C:\Users\arthu\Desktop\deepLuna-main\deepLuna-main\deepLuna.py"
Traceback (most recent call last):
  File "C:\Users\arthu\Desktop\deepLuna-main\deepLuna-main\deepLuna.py", line 7, in <module>
    from tkinter.filedialog import askopenfilename, asksaveasfile
ModuleNotFoundError: No module named 'tkinter.filedialog'

**Comment by Hakanaou** [comment]
Ok, did you install "tkinter" or "Tkinter"? The later seems to be for python 2, and then this might be causing an error. Try to reinstall it maybe.
You have some information about an error similar to yours in this thread: https://stackoverflow.com/questions/31669945/tkinter-import-filedialog-error
