### ISSUE TITLE
feature: linter for time

### ISSUE THREAD

**Issue by R1kaB3rN** [Hakanaou/deepLuna#41]
Hello, before I start making pull requests, I would like to know if checking for preferred time formats that follow the Editing Guidelines would be desirable? This way, most time format errors would be caught early and not later corrected in the future.

**Comment by rschlaikjer** [comment]
Sure https://github.com/Hakanaou/deepLuna/commit/d37afeac374adcb535cc0910e4a53cd99b4348e7
