### ISSUE TITLE
Fail to update scripts

### ISSUE THREAD

**Issue by Lukxie** [Hakanaou/deepLuna#45]
I'm encountering this error while trying to import the tld script from the Tsukihimates/Tsukihime-Translation repo. I'm wondering what  am I doing wrong.
![image](https://github.com/user-attachments/assets/1b7ef08f-bb0c-4718-bf92-ce1a2c98bcc5)
allsrc md5: 5d01e8312f57e8d65f139096ef1d7fa7
script_text md5: e872dc8223f0b52d816ce42fa4cc7374

**Comment by rschlaikjer** [comment]
Looks like you may be trying to import the script as though it were in the legacy (one translation line per line) format. You may have a very old version of the code. Be sure to use the latest master version of you aren't already.
