### ISSUE TITLE
some text missing

### ISSUE THREAD

**Issue by cuobai** [Hakanaou/deepLuna#6]
some text is missing 
e.g. from 031:[189,190,191] to 032:193 
192 is missing
![圖片](https://user-images.githubusercontent.com/74899300/132904493-00ee1ca5-8ffb-4c79-8a72-041b35759e9b.png)

**Comment by Hakanaou** [comment]
Thank you for the report, this issue has been corrected. You can now download the new version of the script (from Code/download zip, I didn't change the release at the moment).
