### ISSUE TITLE
All of the .py files keep immediately closing?

### ISSUE THREAD

**Issue by Rescuro** [Hakanaou/deepLuna#8]
So for some reason every time I try to open deepLuna.py it keeps immediately closing with no text or anything at all. I'm quite confused as I have python downloaded.

**Comment by Arthurfogo7** [comment]
In my case it doesn't even open, even if I have all the modules installed.

**Comment by Hakanaou** [comment]
Which version of python do you have?
Also, how are you launching the script?
Could you be more precise please - do you have some message in the python console of pyzo/IDLE/your editor?
